"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import dj_database_url
from dotenv import load_dotenv
import os
from urllib.parse import urlparse

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Locate where the .env is
load_dotenv(os.path.join(BASE_DIR, ".env"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY", "")
DJANGO_HOST = os.getenv("DJANGO_HOST", "")
LASTFM_API_KEY = os.getenv("LASTFM_API_KEY", "")
LASTFM_API_SHARED_SECRET = os.getenv("LASTFM_API_SHARED_SECRET", "")
DATABASE_URL = os.getenv("DATABASE_URL", "")
LAST_FM_CALLBACK_URL = f"{DJANGO_HOST}/api/lastfm/callback/" # Callback for last.fm to return from auth

# Frontend host used for post-auth redirects. Configurable so dev vs
# prod can use different hostnames. Defaults to the Vercel production URL.
FRONTEND_HOST = os.getenv("FRONTEND_HOST", "https://firstfm.vercel.app")

# SECURITY WARNING: don't run with debug turned on in production!
# Allow enabling DEBUG via environment for local development only.
DJANGO_DEBUG = os.getenv("DJANGO_DEBUG", "False")
DEBUG = DJANGO_DEBUG.lower() in ("1", "true", "yes")

# For SECURE_SSL_REDIRECT
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Redirect HTTP to HTTPS in production; in DEBUG leave as False so dev server
# doesn't attempt redirects to HTTPS (which the built-in server can't handle).
SECURE_SSL_REDIRECT = bool(DEBUG) == False

# CSRF / cookie security
CSRF_USE_SESSIONS = True
if DEBUG:
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SAMESITE = "Lax"
    SESSION_COOKIE_SAMESITE = "Lax"
    # disable HSTS locally
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False
else:
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SAMESITE = "None"
    SESSION_COOKIE_SAMESITE = "None"
    SECURE_HSTS_SECONDS = 86400
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# Build ALLOWED_HOSTS robustly.
allowed = {"firstfm.vercel.app"}

# If DJANGO_HOST is set, add its hostname portion.
if DJANGO_HOST:
    try:
        parsed = urlparse(DJANGO_HOST)
        host = parsed.hostname or DJANGO_HOST
        allowed.add(host)
    except Exception:
        allowed.add(DJANGO_HOST)

# Always allow localhost in development/debug mode
if DEBUG:
    allowed.update({"localhost", "127.0.0.1"})

ALLOWED_HOSTS = list(allowed)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'musicRecommendationService',
    'corsheaders',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS / CSRF trusted origins.
frontend_origins = [FRONTEND_HOST]
if DEBUG:
    frontend_origins.extend(["http://localhost:3000", "http://127.0.0.1:3000"])

CORS_ALLOWED_ORIGINS = frontend_origins

CSRF_TRUSTED_ORIGINS = frontend_origins

CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# This is so we can insert a database url via an environment variable for production here
if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(
            os.environ["DATABASE_URL"],
            conn_max_age=60,
        ),
        'OPTIONS': {'sslmode': 'require'},
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "build.sqlite3"
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
